### ISSUE TITLE
Stable identification of cameras

### ISSUE THREAD

**Issue by cTurtle98** [CabrilloRoboticsClub/cabrillo_rov_2023#128]
the cameras need to be refered to by `/dev/video/by-*/` instead of by the `/dev/video*` so devices dont swap around between reboots

**Comment by DerVerrater** [comment]
The ROV's cameras have physical locations that are important to their function. It's not sufficient to simply have the feed, we must also know the location associated with it.

### The problem

Device node names (`/dev/video*`) don't know or offer location information, and the device behind the node will be randomly assigned on boot. `udev` will create device nodes as it encounters them -- i.e.: In no particular order. The name `/dev/video0` tells us nothing about the device's location, nor does it even tell us if it's our Arducam or the RaspiCam.

### Solution

Select devices by their bus location

This raises a design question, however. Do we:

- Require that devices are installed in specific ports so that we can guarantee their bus location. Or...
- Provide a mapping file to match paths to some internal name.

The benefits of a mapping file are mostly seen in projects that have a substantial spread of configurations -- our is not this, and it doesn't seem like we ever plan on it becoming this. I think it's sufficient to check the hardware for it's port arrangement, and write those device paths into our code -- either the Python source itself, or the various ROS config files.
