### ISSUE TITLE
Re-Enable IMU

### ISSUE THREAD

**Issue by OrionOth** [CabrilloRoboticsClub/cabrillo_rov_2023#152]
#151 disabled the IMU because we were having problems and weren't using it at the time. We do need the IMU, however.

**Comment by mike-matera** [comment]
I think we should do two things: 

1. Change the BNO085 into the "cooked" mode where it reports a simple orientation vector. 
2. Read the sensor inside of a `try`/`except`/ block so that a hardware failure (which is common on this device as it's I2C support is [broken](https://learn.adafruit.com/adafruit-9-dof-orientation-imu-fusion-breakout-bno085))

The ROS publisher can publish an orientation vector which will be easily consumed by a display that informs the pilot of the ROV's orientation.
